### PR TITLE
style: opacity on background

### PR DESCRIPTION
**Pull request by iam4x**
screen shot 2016-10-06 at 20 20 25

<3

### CODE REVIEW

**Comment by SamVerschueren** [comment]
I'm personally not really a big fan of adding opacity to the terminal.

**Comment by iam4x** [comment]
This is not intended to be merged, just to show people the changes needed for opacity support on OSX 👍 

It will never match everyone tastes or everyone will be used the same terminal colors on earth 💃

**Comment by SamVerschueren** [comment]
It would be nice if you could easily override only the background color without forking this. But maybe it is supported?

**Comment by sindresorhus** [comment]
You can override the any of the colors in your `.hyperterm.js` file.

**Comment by sindresorhus** [comment]
Same opinion as Sam about transparency.

**Comment by iam4x** [comment]
@sindresorhus In fact if you override your backgroundColor into `~/.hyper.js` it doesnt work.

**Comment by SamVerschueren** [comment]
Maybe create an issue in the hyperterm repo and link it from here? Would give it a 👍 because I would understand that people like a certain theme, except for maybe one or two colors.

**Comment by sindresorhus** [comment]
See: https://github.com/zeit/hyper/pull/197

**Comment by denniseffing** [comment]
Okay so changing the backgroundColor in my .hyper.js file doesn't have any effect. 
As far as I understand, this is an issue created by the hyper-snazzy theme and not by hyper itself because transparency seems to work as intended as was confirmed in zeit/hyper#197. Is there any way to enable the transparency with hyper-snazzy or not?

**Pull request closed without merging**
